/** Demo data - seed script aur in-memory demo mode dono isi ko use karte hain. */

export const sampleUsers = [
  {
    name: 'Library Admin',
    email: 'admin@university.edu.pk',
    password: 'admin123',
    role: 'admin',
    rollNo: 'ADMIN-001',
    department: 'Library',
    phone: '0300-1234567',
  },
  {
    name: 'Ariba Tahir',
    email: 'ariba@university.edu.pk',
    password: 'student123',
    role: 'student',
    rollNo: 'BSCS-F21-001',
    department: 'Computer Science',
    phone: '0301-1111111',
  },
  {
    name: 'Hamza Khan',
    email: 'hamza@university.edu.pk',
    password: 'student123',
    role: 'student',
    rollNo: 'BSCS-F21-042',
    department: 'Computer Science',
    phone: '0302-2222222',
  },
  {
    name: 'Sana Malik',
    email: 'sana@university.edu.pk',
    password: 'student123',
    role: 'student',
    rollNo: 'BSSE-F22-017',
    department: 'Software Engineering',
    phone: '0303-3333333',
  },
];

export const sampleBooks = [
  {
    title: 'Introduction to Algorithms',
    author: 'Thomas H. Cormen',
    isbn: '9780262046305',
    category: 'Computer Science',
    publisher: 'MIT Press',
    publishYear: 2022,
    edition: '4th',
    shelfLocation: 'CS-A-01',
    totalCopies: 4,
    description:
      'Algorithms ki comprehensive kitaab - sorting, graphs, dynamic programming aur complexity analysis.',
  },
  {
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    isbn: '9780132350884',
    category: 'Software Engineering',
    publisher: 'Prentice Hall',
    publishYear: 2008,
    edition: '1st',
    shelfLocation: 'SE-B-04',
    totalCopies: 3,
    description: 'Saaf, readable aur maintainable code likhne ke usool aur practical examples.',
  },
  {
    title: 'Database System Concepts',
    author: 'Abraham Silberschatz',
    isbn: '9780078022159',
    category: 'Database',
    publisher: 'McGraw-Hill',
    publishYear: 2019,
    edition: '7th',
    shelfLocation: 'DB-C-02',
    totalCopies: 5,
    description: 'Relational model, SQL, normalization, transactions aur query processing.',
  },
  {
    title: 'Computer Networks',
    author: 'Andrew S. Tanenbaum',
    isbn: '9780132126953',
    category: 'Networking',
    publisher: 'Pearson',
    publishYear: 2021,
    edition: '6th',
    shelfLocation: 'NW-D-03',
    totalCopies: 3,
    description: 'Network layers, protocols, routing aur network security ka detailed taaruf.',
  },
  {
    title: 'Operating System Concepts',
    author: 'Abraham Silberschatz',
    isbn: '9781119800361',
    category: 'Operating Systems',
    publisher: 'Wiley',
    publishYear: 2021,
    edition: '10th',
    shelfLocation: 'OS-A-07',
    totalCopies: 4,
    description: 'Processes, threads, scheduling, memory management aur file systems.',
  },
  {
    title: 'Artificial Intelligence: A Modern Approach',
    author: 'Stuart Russell',
    isbn: '9780134610993',
    category: 'Artificial Intelligence',
    publisher: 'Pearson',
    publishYear: 2020,
    edition: '4th',
    shelfLocation: 'AI-E-01',
    totalCopies: 2,
    description: 'Search, knowledge representation, machine learning aur intelligent agents.',
  },
  {
    title: 'Eloquent JavaScript',
    author: 'Marijn Haverbeke',
    isbn: '9781593279509',
    category: 'Web Development',
    publisher: 'No Starch Press',
    publishYear: 2018,
    edition: '3rd',
    shelfLocation: 'WD-F-02',
    totalCopies: 3,
    description: 'JavaScript language, DOM, asynchronous programming aur Node.js basics.',
  },
  {
    title: 'Software Engineering',
    author: 'Ian Sommerville',
    isbn: '9780133943030',
    category: 'Software Engineering',
    publisher: 'Pearson',
    publishYear: 2015,
    edition: '10th',
    shelfLocation: 'SE-B-01',
    totalCopies: 4,
    description: 'Requirements engineering, design, testing aur project management.',
  },
  {
    title: 'Discrete Mathematics and Its Applications',
    author: 'Kenneth H. Rosen',
    isbn: '9781259676512',
    category: 'Mathematics',
    publisher: 'McGraw-Hill',
    publishYear: 2018,
    edition: '8th',
    shelfLocation: 'MT-G-05',
    totalCopies: 5,
    description: 'Logic, sets, relations, graph theory aur combinatorics.',
  },
  {
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt',
    isbn: '9780135957059',
    category: 'Software Engineering',
    publisher: 'Addison-Wesley',
    publishYear: 2019,
    edition: '2nd',
    shelfLocation: 'SE-B-09',
    totalCopies: 2,
    description: 'Practical tips aur habits jo developer ko behtar banate hain.',
  },
  {
    title: 'Head First Design Patterns',
    author: 'Eric Freeman',
    isbn: '9781492078005',
    category: 'Software Engineering',
    publisher: "O'Reilly",
    publishYear: 2021,
    edition: '2nd',
    shelfLocation: 'SE-B-11',
    totalCopies: 3,
    description: 'Design patterns ko asaan visual tareeqe se samjhaya gaya hai.',
  },
  {
    title: 'Cryptography and Network Security',
    author: 'William Stallings',
    isbn: '9780134444284',
    category: 'Information Security',
    publisher: 'Pearson',
    publishYear: 2017,
    edition: '7th',
    shelfLocation: 'IS-H-02',
    totalCopies: 2,
    description: 'Encryption algorithms, key management aur network security protocols.',
  },
];
